version: '3.4'

services:
  scraper:
    container_name: scraper
    labels:
      - "traefik.backend=craw4-scraper"
      - "traefik.frontend.rule=PathPrefixStrip: /craw4-headless"
    user: root # avoids ton of volume mounting headaches in dev mode.
    build: 
      context: .
      target: builder
    volumes:
      - .:/go/src/craw4-scraper
    ports:
      - 3737
      # - 3738 # health check endpoint
    environment:
      - APP_ENV=development
    command: scripts/run.sh

# @see: https://github.com/pilu/fresh
# @alt @see: https://github.com/codegangsta/gin
